'use strict';

const EV_COLS = {
  'Sports':       '#166534',
  'Gaming':       '#4C1D95',
  'Social':       '#831843',
  'Fitness':      '#1E3A5F',
  'Food & Drink': '#78350F',
  'Wellness':     '#065F46',
  'Music':        '#3B0764',
  'Outdoors':     '#365314',
  'Arts':         '#0C4A6E',
};

const INTERESTS = [
  {e:'⚽',label:'Football'},{e:'🏉',label:'Rugby'},
  {e:'🏎️',label:'Formula 1'},{e:'🏋️',label:'Gym & Fitness'},
  {e:'🏃',label:'Running'},{e:'🧘',label:'Yoga & Wellness'},
  {e:'🥾',label:'Hiking & Outdoors'},{e:'🍛',label:'Food & Dining'},
  {e:'☕',label:'Coffee & Cafés'},{e:'🍺',label:'Pub & Social'},
  {e:'🎮',label:'Video Games'},{e:'🃏',label:'Board Games'},
  {e:'🛍️',label:'Shopping'},{e:'🎵',label:'Live Music'},
  {e:'🎬',label:'Cinema'},{e:'📚',label:'Book Club'},
  {e:'🎨',label:'Arts & Culture'},{e:'🏊',label:'Swimming'},
];

const CITIES = ['London','Manchester','Birmingham','Edinburgh','Bristol','Leeds','Liverpool'];

const EVENTS = [
  {id:'EV001',t:'Premier League Watch Party',cat:'Sports',interests:['Football'],city:'London',venue:"The Crown & Anchor",addr:'22 Fleet St, London EC4Y',date:'2025-07-14',time:'15:00',dur:'3 hrs',price:'Free',going:24,max:40,e:'⚽',dist:1.2,desc:"Watch the big match with fellow fans at one of London\'s best sports pubs. Great banter, cold drinks and proper football all afternoon.",tags:['Football','Sports','Social'],ft:'Both',ages:'18+'},
  {id:'EV002',t:'Magic: The Gathering Draft Night',cat:'Gaming',interests:['Board Games'],city:'London',venue:'Playset Games',addr:'14 Carnaby St, London W1F',date:'2025-07-11',time:'19:00',dur:'3 hrs',price:'£8',going:12,max:20,e:'🃏',dist:0.8,desc:'Friendly booster draft evening  -  cards provided. All skill levels welcome from first-timers to seasoned veterans. Great way to meet other players in the city.',tags:['Gaming','Cards','Strategy'],ft:'Both',ages:'All ages'},
  {id:'EV003',t:'Westfield Shopping Trip',cat:'Social',interests:['Shopping'],city:'London',venue:'Westfield Stratford',addr:'Montfichet Rd, London E20',date:'2025-07-15',time:'11:00',dur:'4 hrs',price:'Free',going:8,max:15,e:'🛍️',dist:4.2,desc:"Meet new friends over a fun shopping afternoon at Westfield. We\'ll grab lunch together and explore the shops  -  perfect if you\'re new to the area.",tags:['Shopping','Social','Casual'],ft:'Girls',ages:'All ages'},
  {id:'EV004',t:'F1 Grand Prix Watch Party',cat:'Sports',interests:['Formula 1'],city:'London',venue:'Skylight Rooftop Bar',addr:'Tobacco Dock, London E1W',date:'2025-07-22',time:'13:00',dur:'3 hrs',price:'£5',going:35,max:60,e:'🏎️',dist:2.1,desc:"Watch the Grand Prix on the big screen with a crowd of passionate F1 fans. Cocktails on the rooftop, great atmosphere and non-stop racing chat.",tags:['F1','Sports','Social'],ft:'Both',ages:'18+'},
  {id:'EV005',t:'Morning Run Club',cat:'Fitness',interests:['Running','Gym & Fitness'],city:'London',venue:'Victoria Park',addr:'Grove Rd, London E3',date:'2025-07-08',time:'07:30',dur:'1 hr',price:'Free',going:18,max:30,e:'🏃',dist:3.5,desc:'A friendly 5K run around Victoria Park for all abilities. No pace pressure  -  just fresh air, good chat, and coffee at the park café afterwards.',tags:['Running','Fitness','Outdoors'],ft:'Both',ages:'All ages'},
  {id:'EV006',t:'Brick Lane Food Tour',cat:'Food & Drink',interests:['Food & Dining'],city:'London',venue:'Brick Lane',addr:'Brick Lane, London E1',date:'2025-07-13',time:'18:30',dur:'2.5 hrs',price:'£10–25',going:14,max:20,e:'🍛',dist:1.9,desc:"Explore Brick Lane\'s legendary food scene together. We\'ll sample dishes from multiple stalls and restaurants  -  an absolute must for foodies.",tags:['Food','Indian','Social'],ft:'Both',ages:'All ages'},
  {id:'EV007',t:'Sunday Yoga in Hyde Park',cat:'Wellness',interests:['Yoga & Wellness'],city:'London',venue:'Hyde Park',addr:'Hyde Park, London W2',date:'2025-07-09',time:'09:00',dur:'1 hr',price:'Free',going:22,max:40,e:'🧘',dist:2.8,desc:"Start your Sunday with a relaxing yoga session in Hyde Park. All levels welcome  -  just bring a mat and good energy. Coffee and chat afterwards!",tags:['Yoga','Wellness','Outdoors'],ft:'Both',ages:'All ages'},
  {id:'EV008',t:'Manchester Derby Watch Party',cat:'Sports',interests:['Football'],city:'Manchester',venue:'The Printworks',addr:'27 Withy Grove, Manchester',date:'2025-07-14',time:'16:30',dur:'2 hrs',price:'Free',going:42,max:80,e:'⚽',dist:0.5,desc:"City vs United  -  the biggest derby in football. Watch it with hundreds of passionate fans at one of Manchester\'s most iconic entertainment venues.",tags:['Football','Derby','Social'],ft:'Both',ages:'18+'},
  {id:'EV009',t:'Quiz Night at The Refuge',cat:'Social',interests:['Pub & Social'],city:'Manchester',venue:'The Refuge',addr:'Oxford St, Manchester M60',date:'2025-07-10',time:'19:30',dur:'2 hrs',price:'£3',going:20,max:40,e:'🧠',dist:0.3,desc:"Come solo or in a group  -  we\'ll pair you up with a team! Six rounds covering sport, music, film and general knowledge. Prizes for the top three teams.",tags:['Quiz','Social','Pub'],ft:'Both',ages:'18+'},
  {id:'EV010',t:'Northern Quarter Coffee Crawl',cat:'Food & Drink',interests:['Coffee & Cafés'],city:'Manchester',venue:'Northern Quarter',addr:'Northern Quarter, Manchester',date:'2025-07-12',time:'10:00',dur:'3 hrs',price:'Free (pay per café)',going:9,max:15,e:'☕',dist:0.6,desc:"Visit four of Manchester\'s best independent coffee shops in the Northern Quarter. Perfect for people new to the city who want to explore and make friends.",tags:['Coffee','Social','Casual'],ft:'Both',ages:'All ages'},
  {id:'EV011',t:'Gym Buddies Session',cat:'Fitness',interests:['Gym & Fitness'],city:'Birmingham',venue:'PureGym Birmingham',addr:'Corporation St, Birmingham B2',date:'2025-07-10',time:'18:00',dur:'1.5 hrs',price:'£6 day pass',going:6,max:12,e:'🏋️',dist:0.4,desc:"Train with new gym buddies and share tips and programmes. Weights, cardio or classes  -  all levels welcome. Protein shakes after!",tags:['Gym','Fitness','Health'],ft:'Both',ages:'All ages'},
  {id:'EV012',t:'Balti Triangle Food Tour',cat:'Food & Drink',interests:['Food & Dining'],city:'Birmingham',venue:'Balti Triangle',addr:'Ladypool Rd, Birmingham B12',date:'2025-07-20',time:'19:00',dur:'2 hrs',price:'£15–20',going:11,max:16,e:'🍲',dist:3.1,desc:"Birmingham\'s Balti Triangle is world-famous for good reason. Join fellow foodies and try authentic baltis at the area\'s best restaurants.",tags:['Food','Indian','Culture'],ft:'Both',ages:'All ages'},
  {id:'EV013',t:'Six Nations Rugby Screening',cat:'Sports',interests:['Rugby'],city:'Edinburgh',venue:'The Hanging Bat',addr:'133 Lothian Rd, Edinburgh',date:'2025-07-15',time:'14:00',dur:'2 hrs',price:'Free',going:31,max:50,e:'🏉',dist:0.2,desc:"Scotland in action! Watch the match in one of Edinburgh\'s best bars with a passionate home crowd. The atmosphere is always electric.",tags:['Rugby','Sports','Social'],ft:'Both',ages:'18+'},
  {id:'EV014',t:"Arthur\'s Seat Hike",cat:'Outdoors',interests:['Hiking & Outdoors'],city:'Edinburgh',venue:'Holyrood Park',addr:"Queen\'s Dr, Edinburgh EH8",date:'2025-07-08',time:'09:00',dur:'2.5 hrs',price:'Free',going:15,max:25,e:'🥾',dist:1.0,desc:"Hike up Arthur\'s Seat for breathtaking views over Edinburgh. Moderate difficulty  -  good trainers recommended. Coffee and cake at the bottom afterwards!",tags:['Hiking','Outdoors','Nature'],ft:'Both',ages:'All ages'},
  {id:'EV015',t:'Board Game Night',cat:'Gaming',interests:['Board Games'],city:'Bristol',venue:'Chance & Counters',addr:'20 Christmas Steps, Bristol',date:'2025-07-11',time:'18:30',dur:'3 hrs',price:'£5',going:16,max:24,e:'🎲',dist:0.3,desc:"Bristol\'s favourite board game café! Choose from over 500 games, enjoy great food and drinks, and meet fellow enthusiasts. Solos very welcome.",tags:['Board Games','Social','Indoor'],ft:'Both',ages:'All ages'},
  {id:'EV016',t:'Live Music at Thekla',cat:'Music',interests:['Live Music'],city:'Bristol',venue:'Thekla',addr:'East Mud Dock, Bristol BS1',date:'2025-07-13',time:'20:00',dur:'3 hrs',price:'£12',going:45,max:80,e:'🎵',dist:0.8,desc:"Live indie music aboard Bristol\'s iconic floating music venue. Come solo  -  the crowd is always warm and welcoming, and the vibes are always incredible.",tags:['Music','Live','Nightlife'],ft:'Both',ages:'18+'},
  {id:'EV017',t:'Leeds Indie Cinema Night',cat:'Arts',interests:['Cinema'],city:'Leeds',venue:'Hyde Park Picture House',addr:'Brudenell Rd, Leeds LS6',date:'2025-07-16',time:'19:30',dur:'2.5 hrs',price:'£9',going:20,max:35,e:'🎬',dist:2.3,desc:"Screen a classic indie film and discuss it over drinks afterwards. A relaxed, welcoming crowd  -  perfect if you love film and want to meet like-minded people.",tags:['Cinema','Arts','Social'],ft:'Both',ages:'All ages'},
  {id:'EV018',t:'Liverpool Book Club',cat:'Social',interests:['Book Club'],city:'Liverpool',venue:'Bold Street Coffee',addr:'89 Bold St, Liverpool L1',date:'2025-07-17',time:'18:00',dur:'2 hrs',price:'Free',going:10,max:16,e:'📚',dist:0.5,desc:"Monthly book club meeting  -  this month we\'re reading The Thursday Murder Club by Richard Osman. No need to have finished it, just come along and enjoy the chat!",tags:['Books','Social','Casual'],ft:'Both',ages:'All ages'},

  // ── Wellness ────────────────────────────────────────────
  {id:'EV019',t:'Morning Meditation Circle',cat:'Wellness',interests:['Yoga & Wellness'],city:'London',venue:'Barbican Conservatory',addr:'Silk St, London EC2Y',date:'2025-07-06',time:'08:00',dur:'1 hr',price:'Free',going:19,max:30,e:'🧘',dist:1.4,desc:'Start your week with a guided group meditation in the beautiful indoor garden at the Barbican. No experience needed  -  just bring a mat and an open mind.',tags:['Meditation','Wellness','Mindfulness'],ages:'All ages',ft:'Both'},
  {id:'EV020',t:'Sound Bath Session',cat:'Wellness',interests:['Yoga & Wellness'],city:'Manchester',venue:'Refuge Wellness',addr:'Oxford St, Manchester M60',date:'2025-07-19',time:'18:30',dur:'1.5 hrs',price:'£12',going:14,max:20,e:'🔔',dist:0.3,desc:'Lie back and let the vibrations of crystal singing bowls wash over you. A deeply relaxing experience ideal for stress relief and mental clarity. Mats and blankets provided.',tags:['Sound Bath','Wellness','Relaxation'],ages:'All ages',ft:'Both'},
  {id:'EV021',t:'Breathwork & Cold Plunge',cat:'Wellness',interests:['Yoga & Wellness','Gym & Fitness'],city:'Bristol',venue:'Hotwells Lido',addr:'Hotwell Rd, Bristol BS8',date:'2025-07-20',time:'07:30',dur:'1.5 hrs',price:'£10',going:12,max:20,e:'❄️',dist:1.1,desc:'Learn the Wim Hof breathing method then take a supervised cold plunge at Bristol\'s open-air lido. Energising, community-led and surprisingly addictive.',tags:['Breathwork','Cold Water','Fitness'],ages:'18+',ft:'Both'},

  // ── Outdoors ────────────────────────────────────────────
  {id:'EV022',t:'Box Hill Sunrise Hike',cat:'Outdoors',interests:['Hiking & Outdoors'],city:'London',venue:'Box Hill, Surrey',addr:'Box Hill Rd, Dorking RH5',date:'2025-07-12',time:'06:00',dur:'4 hrs',price:'Free',going:21,max:35,e:'🌅',dist:18.4,desc:'Catch the sunrise from the top of Box Hill with a friendly group of hikers. Moderate 8km route, stunning views over the Surrey Hills, and breakfast at the cafe at the top.',tags:['Hiking','Sunrise','Nature'],ages:'All ages',ft:'Both'},
  {id:'EV023',t:'Canal Kayaking Trip',cat:'Outdoors',interests:['Hiking & Outdoors','Swimming'],city:'Birmingham',venue:'Gas Street Basin',addr:'Gas St, Birmingham B1',date:'2025-07-13',time:'10:00',dur:'3 hrs',price:'£25',going:10,max:14,e:'🚣',dist:0.6,desc:'Paddle through Birmingham\'s historic canal network with an experienced guide. Equipment and brief training provided  -  no prior kayaking experience necessary.',tags:['Kayaking','Outdoors','Water'],ages:'16+',ft:'Both'},
  {id:'EV024',t:'Night Cycling Ride',cat:'Outdoors',interests:['Hiking & Outdoors'],city:'London',venue:'Southbank',addr:'Southbank, London SE1',date:'2025-07-18',time:'21:00',dur:'2.5 hrs',price:'Free',going:28,max:50,e:'🚲',dist:1.6,desc:'Explore London by night on two wheels. A relaxed 15-mile circular route taking in the City, Canary Wharf and back along the Thames. All fitness levels welcome  -  just bring a working bike and lights.',tags:['Cycling','Night Ride','London'],ages:'16+',ft:'Both'},

  // ── Music ───────────────────────────────────────────────
  {id:'EV025',t:'Jazz & Cocktails Night',cat:'Music',interests:['Live Music','Pub & Social'],city:'London',venue:'Ronnie Scott\'s',addr:'47 Frith St, London W1D',date:'2025-07-11',time:'20:00',dur:'3 hrs',price:'£18',going:38,max:60,e:'🎷',dist:1.2,desc:'A magical evening of live jazz at one of the world\'s most iconic venues. Come solo or in a group  -  the warm atmosphere makes it easy to meet fellow music lovers over cocktails.',tags:['Jazz','Live Music','Cocktails'],ages:'18+',ft:'Both'},
  {id:'EV026',t:'Open Mic Night',cat:'Music',interests:['Live Music'],city:'Leeds',venue:'Brudenell Social Club',addr:'33 Queens Rd, Leeds LS6',date:'2025-07-10',time:'19:00',dur:'3 hrs',price:'£3',going:24,max:60,e:'🎤',dist:2.1,desc:'Whether you want to perform or just enjoy a great night out, this monthly open mic welcomes all levels. Expect original songs, spoken word, comedy and the occasional surprise act.',tags:['Open Mic','Live Music','Social'],ages:'18+',ft:'Both'},
  {id:'EV027',t:'Vinyl Record Swap',cat:'Music',interests:['Live Music','Arts & Culture'],city:'Manchester',venue:'Vinyl Exchange',addr:'18 Market St, Manchester M1',date:'2025-07-09',time:'11:00',dur:'3 hrs',price:'Free',going:15,max:30,e:'💿',dist:0.4,desc:'Bring records you no longer play, swap them for ones you\'ll love. A relaxed morning for music obsessives of all tastes  -  DJs on the decks all morning and free coffee for swappers.',tags:['Vinyl','Records','Music'],ages:'All ages',ft:'Both'},

  // ── Arts ────────────────────────────────────────────────
  {id:'EV028',t:'Life Drawing Class',cat:'Arts',interests:['Arts & Culture'],city:'London',venue:'Hackney Arts Centre',addr:'1 Reading Ln, London E8',date:'2025-07-08',time:'19:00',dur:'2 hrs',price:'£8',going:16,max:24,e:'🎨',dist:3.8,desc:'Drop-in life drawing session for all abilities. Paper and charcoal provided  -  just turn up, draw, and enjoy the social atmosphere. A great way to be creative and meet people.',tags:['Art','Drawing','Creative'],ages:'18+',ft:'Both'},
  {id:'EV029',t:'Photography Walk',cat:'Arts',interests:['Arts & Culture','Hiking & Outdoors'],city:'Edinburgh',venue:'Old Town',addr:'Royal Mile, Edinburgh EH1',date:'2025-07-13',time:'14:00',dur:'2 hrs',price:'Free',going:11,max:18,e:'📷',dist:0.5,desc:'Explore the winding closes and dramatic skyline of Edinburgh\'s Old Town through the lens. Phones and cameras equally welcome  -  tips on composition shared by the group as you go.',tags:['Photography','Arts','Edinburgh'],ages:'All ages',ft:'Both'},
  {id:'EV030',t:'Street Art & Mural Tour',cat:'Arts',interests:['Arts & Culture'],city:'Bristol',venue:'Stokes Croft',addr:'Stokes Croft, Bristol BS1',date:'2025-07-12',time:'13:00',dur:'2 hrs',price:'Free',going:18,max:30,e:'🖌️',dist:0.7,desc:'Discover Bristol\'s world-famous street art scene on a guided walking tour through Stokes Croft and Bedminster. Learn the stories behind Banksy\'s murals and dozens of other artists.',tags:['Street Art','Walking','Culture'],ages:'All ages',ft:'Both'},

  // ── Gaming (more) ────────────────────────────────────────
  {id:'EV031',t:'Dungeons & Dragons One-Shot',cat:'Gaming',interests:['Board Games','Gaming'],city:'London',venue:'Draughts Bar',addr:'337 Acton Mews, London E8',date:'2025-07-09',time:'18:00',dur:'4 hrs',price:'£6',going:7,max:8,e:'🐉',dist:4.1,desc:'An introductory D&D adventure for beginners and veterans alike. Pre-made characters provided  -  just bring your imagination. Dungeon master will guide you through everything.',tags:['D&D','Tabletop','Fantasy'],ages:'All ages',ft:'Both'},
  {id:'EV032',t:'Retro Gaming Night',cat:'Gaming',interests:['Gaming','Video Games'],city:'Leeds',venue:'Loading Bar Leeds',addr:'Merrion St, Leeds LS2',date:'2025-07-11',time:'19:00',dur:'3 hrs',price:'£5',going:22,max:40,e:'🕹️',dist:1.0,desc:'Classic consoles, arcade cabinets and great company. Play SNES, N64, Mega Drive and more with fellow retro fans. Entry includes unlimited gaming all night.',tags:['Retro Gaming','Social','Arcade'],ages:'18+',ft:'Both'},

  // ── Fitness (more) ──────────────────────────────────────
  {id:'EV033',t:'Beginner Climbing Session',cat:'Fitness',interests:['Gym & Fitness'],city:'London',venue:'The Castle Climbing Centre',addr:'Green Lanes, London N4',date:'2025-07-10',time:'18:30',dur:'2 hrs',price:'£16',going:10,max:16,e:'🧗',dist:5.2,desc:'Try indoor bouldering for the first time in a friendly group. Instructors will walk you through the basics  -  shoes and chalk provided. A full-body workout that doesn\'t feel like one.',tags:['Climbing','Fitness','Beginners'],ages:'16+',ft:'Both'},
  {id:'EV034',t:'5-a-Side Football',cat:'Fitness',interests:['Football','Gym & Fitness'],city:'Birmingham',venue:'Goals Birmingham',addr:'Garrison Ln, Birmingham B9',date:'2025-07-15',time:'19:00',dur:'1.5 hrs',price:'£5',going:8,max:10,e:'⚽',dist:2.8,desc:'Weekly mixed 5-a-side game for all abilities. We split into balanced teams on the night  -  just turn up ready to run around and have fun. Absolute beginners welcome.',tags:['Football','5-a-side','Fitness'],ages:'18+',ft:'Both'},
];

const SAMPLE_ATTENDEES = [
  {name:'Alex K',color:'#F97316'},{name:'Sam R',color:'#8B5CF6'},
  {name:'Jordan P',color:'#3B82F6'},{name:'Casey M',color:'#EF4444'},
  {name:'Riley T',color:'#10B981'},{name:'Morgan W',color:'#F59E0B'},
  {name:'Taylor B',color:'#EC4899'},{name:'Jamie L',color:'#0891B2'},
  {name:'Charlie S',color:'#84CC16'},{name:'Drew N',color:'#F97316'},
  {name:'Avery H',color:'#A855F7'},{name:'Quinn F',color:'#14B8A6'},
];
